"""Static, curated general-purpose reference for common medications — the
Tier 2 fallback in the "why" explanation shown on the patient care page (see
patient_access/service.py's _resolve_medication_why()).

This is deliberately NOT generated by an LLM, and NOT specific to any patient:
it is the same kind of general information printed on a pharmacy medication
guide (e.g. "commonly used to treat high blood pressure"), never a claim
about why THIS patient was prescribed it. Only used when the clinician's own
instruction text didn't state a reason (see MedicationFacts.reason in
app/ai/schemas.py) — Tier 1 (the clinician's own stated reason) always takes
priority when present.

Deliberately small and hand-curated rather than comprehensive: a prototype
covering ~15-20 common medications, not a substitute for a real drug-
information database (see the project's production plan: connect an
approved clinical/drug-information source and replace this table wholesale,
without changing anything that reads from it — lookup_medication_purpose's
signature stays the same either way). If a medication isn't here, no general
information is shown — never a guess, and never an LLM asked to fill the gap
(an earlier prototype version did that; it was removed as a safety
correction — see patient_access/service.py's resolve_why docstring).
"""

# Keyed by lowercased medication name. Text is intentionally general ("commonly
# used to...") and lists the primary, well-established indications only — no
# off-label or rare uses, since precision here matters more than completeness.
MEDICATION_PURPOSE: dict[str, str] = {
    "metoprolol": "Commonly used to treat high blood pressure, chest pain, and irregular heartbeats.",
    "lisinopril": "Commonly used to treat high blood pressure and heart failure.",
    "levothyroxine": "Used to treat an underactive thyroid (hypothyroidism).",
    "amoxicillin": "An antibiotic commonly used to treat bacterial infections.",
    "warfarin": "A blood thinner commonly used to prevent and treat blood clots, and to reduce stroke risk in certain heart conditions.",
    "ibuprofen": "Commonly used to relieve pain, reduce fever, and reduce swelling.",
    "naproxen": "Commonly used to relieve pain, reduce fever, and reduce swelling, such as from arthritis.",
    "metformin": "Commonly used to treat type 2 diabetes by helping control blood sugar levels.",
    "amlodipine": "Commonly used to treat high blood pressure and chest pain (angina).",
    "atorvastatin": "Commonly used to lower cholesterol and reduce the risk of heart disease.",
    "losartan": "Commonly used to treat high blood pressure and to help protect the kidneys in certain conditions.",
    "hydrochlorothiazide": "A water pill (diuretic) commonly used to treat high blood pressure and fluid retention.",
    "omeprazole": "Commonly used to treat acid reflux, heartburn, and stomach ulcers by reducing stomach acid.",
    "sertraline": "Commonly used to treat depression and certain anxiety disorders.",
    "albuterol": "Commonly used to relieve and prevent wheezing and shortness of breath from asthma or COPD.",
    "gabapentin": "Commonly used to treat nerve pain and certain types of seizures.",
    "prednisone": "A steroid commonly used to reduce inflammation in a range of conditions, including allergic reactions and autoimmune flares.",
    "aspirin": "Commonly used to relieve pain and reduce fever, and at low doses to help prevent heart attack and stroke.",
    "furosemide": "A water pill (diuretic) commonly used to treat fluid retention and swelling, including from heart failure.",
}


def lookup_medication_purpose(medication_name: str | None) -> str | None:
    if not medication_name:
        return None
    return MEDICATION_PURPOSE.get(medication_name.strip().lower())
