#!/usr/bin/env bash
# HTTPS for the device link on a development machine.
#
# Creates (once) a private development CA, then a server certificate for this
# machine's current LAN address signed by it, and writes the CA certificate
# into the firmware (firmware/include/backend_ca.h, git-ignored) so the band
# can verify the backend. Keys live in ~/.safehaven-dev-tls, never in the repo.
#
#   backend/scripts/dev_tls.sh            # uses `ipconfig getifaddr en0`
#   backend/scripts/dev_tls.sh 10.0.0.5   # or a given address
#
# Then serve the device API over TLS alongside the plain dev server:
#
#   .venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8443 \
#       --ssl-keyfile ~/.safehaven-dev-tls/server.key \
#       --ssl-certfile ~/.safehaven-dev-tls/server.pem
#
# and set SH_BACKEND_URL "https://<address>:8443" in wifi_secrets.h.
#
# When the Mac's address changes (DHCP), re-run this script: only the server
# certificate changes, the CA (and so the firmware) stays the same.
#
# DEVELOPMENT ONLY. A hospital deployment uses a certificate from the
# hospital's own CA or a public one, and that CA goes into backend_ca.h.
set -euo pipefail

IP="${1:-$(ipconfig getifaddr en0 2>/dev/null || true)}"
if [[ -z "$IP" ]]; then
  echo "usage: $0 <LAN IP address>" >&2
  exit 2
fi
DIR="$HOME/.safehaven-dev-tls"
REPO="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$REPO/firmware/include/backend_ca.h"
mkdir -p "$DIR"
chmod 700 "$DIR"
umask 077

if [[ ! -f "$DIR/ca.key" ]]; then
  echo "Creating the development CA (once)..."
  openssl ecparam -name prime256v1 -genkey -noout -out "$DIR/ca.key"
  openssl req -x509 -new -key "$DIR/ca.key" -sha256 -days 3650 \
    -subj "/CN=SAFEHAVEN development CA" \
    -addext "basicConstraints=critical,CA:TRUE" \
    -addext "keyUsage=critical,keyCertSign,cRLSign" \
    -out "$DIR/ca.pem"
fi

echo "Server certificate for $IP..."
openssl ecparam -name prime256v1 -genkey -noout -out "$DIR/server.key"
openssl req -new -key "$DIR/server.key" -subj "/CN=$IP" -out "$DIR/server.csr"
# The address is listed as a DNS name as well as an IP: the band's mbedTLS
# matches the host it dialled against DNS names only, and rejected an
# IP-only certificate (X509 -9984) on the bench.
cat > "$DIR/server.ext" <<EOF
basicConstraints=CA:FALSE
keyUsage=critical,digitalSignature
extendedKeyUsage=serverAuth
subjectAltName=IP:$IP,DNS:$IP,DNS:localhost
EOF
openssl x509 -req -in "$DIR/server.csr" -CA "$DIR/ca.pem" -CAkey "$DIR/ca.key" -CAcreateserial \
  -days 397 -sha256 -extfile "$DIR/server.ext" -out "$DIR/server.pem" 2>/dev/null
rm -f "$DIR/server.csr" "$DIR/server.ext"

umask 022
{
  echo "// GENERATED by backend/scripts/dev_tls.sh — development CA, git-ignored."
  echo "// The band only talks to a backend whose certificate this CA signed."
  echo "#pragma once"
  echo "#define SH_BACKEND_CA \\"
  sed 's/.*/  "&\\n" \\/' "$DIR/ca.pem"
  echo "  \"\""
} > "$OUT"

openssl verify -CAfile "$DIR/ca.pem" "$DIR/server.pem"
echo "CA for the firmware: $OUT"
echo "Backend URL for the band: https://$IP:8443"
