"""add capture_method to instruction_versions

Revision ID: 06a3cd513143
Revises: 0ec7c07af10f
Create Date: 2026-09-15 05:38:06.666133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '06a3cd513143'
down_revision: Union[str, None] = '0ec7c07af10f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # The autogenerated form (inline sa.Enum on add_column) does NOT create
    # the Postgres type — add_column, unlike create_table, never emits the
    # CREATE TYPE, so it fails with "type ... does not exist". Same gotcha
    # already hit twice in this project; create the type explicitly and tell
    # the column not to try.
    op.execute("CREATE TYPE instruction_capture_method AS ENUM ('TYPED', 'DICTATED')")
    op.add_column(
        'instruction_versions',
        sa.Column(
            'capture_method',
            postgresql.ENUM('TYPED', 'DICTATED', name='instruction_capture_method', create_type=False),
            nullable=True,
        ),
    )


def downgrade() -> None:
    op.drop_column('instruction_versions', 'capture_method')
    op.execute("DROP TYPE instruction_capture_method")
