"""add not-given outcome to administration events

Revision ID: 09f46a08bd9b
Revises: 9999e713dbb8
Create Date: 2026-09-23 02:47:28.424444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '09f46a08bd9b'
down_revision: Union[str, None] = '9999e713dbb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # add_column never emits the CREATE TYPE (unlike create_table), so the
    # autogenerated form fails with "type does not exist". Same gotcha as the
    # capture_method and identification_method enums before it.
    op.execute(
        "CREATE TYPE administration_not_given_reason AS ENUM "
        "('REFUSED', 'HELD', 'PATIENT_UNAVAILABLE', 'VOMITED', 'OTHER')"
    )
    op.add_column(
        'administration_events',
        sa.Column(
            'not_given_reason',
            postgresql.ENUM(
                'REFUSED', 'HELD', 'PATIENT_UNAVAILABLE', 'VOMITED', 'OTHER',
                name='administration_not_given_reason', create_type=False,
            ),
            nullable=True,
        ),
    )
    op.add_column('administration_events', sa.Column('not_given_note', sa.Text(), nullable=True))
    op.add_column('administration_events', sa.Column('not_given_by', sa.UUID(), nullable=True))
    op.add_column('administration_events', sa.Column('not_given_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'administration_events', 'users', ['not_given_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'administration_events', type_='foreignkey')
    op.drop_column('administration_events', 'not_given_at')
    op.drop_column('administration_events', 'not_given_by')
    op.drop_column('administration_events', 'not_given_note')
    op.drop_column('administration_events', 'not_given_reason')
    op.execute('DROP TYPE administration_not_given_reason')
    # ### end Alembic commands ###
