"""add high-alert co-sign fields to administration_events

Revision ID: 0ec7c07af10f
Revises: 4a80500a5ae6
Create Date: 2026-09-14 11:45:38.030546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec7c07af10f'
down_revision: Union[str, None] = '4a80500a5ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default needed here (not just the ORM-level default) — existing
    # rows must be backfilled to False, since this column is NOT NULL and
    # the table already has data from before this migration.
    op.add_column(
        'administration_events',
        sa.Column('identified_high_alert', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('administration_events', 'identified_high_alert', server_default=None)
    op.add_column('administration_events', sa.Column('co_signed_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'administration_events', 'users', ['co_signed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'administration_events', type_='foreignkey')
    op.drop_column('administration_events', 'co_signed_by')
    op.drop_column('administration_events', 'identified_high_alert')
    # ### end Alembic commands ###
