"""create patients table

Revision ID: 10a058489a8a
Revises: 66b246cc61e8
Create Date: 2026-09-02 13:24:51.891502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '10a058489a8a'
down_revision: Union[str, None] = '66b246cc61e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Backs patient_code's server_default below; must exist before the table is created.
    op.execute("CREATE SEQUENCE patient_code_seq START WITH 1001")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_code', sa.String(length=20), server_default=sa.text("'P' || nextval('patient_code_seq')"), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=True),
    sa.Column('preferred_language', sa.Enum('ENGLISH', 'TELUGU', 'HINDI', name='patient_language'), nullable=False),
    sa.Column('admission_status', sa.Enum('ACTIVE', 'DISCHARGED', name='patient_admission_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_patient_code'), 'patients', ['patient_code'], unique=True)
    # ### end Alembic commands ###

    # Ties the sequence's lifecycle to the column it backs (dropped automatically with it).
    op.execute("ALTER SEQUENCE patient_code_seq OWNED BY patients.patient_code")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_patient_code'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
    # Table drop cascades to the owned sequence, so no explicit DROP SEQUENCE needed here.

    # op.drop_table doesn't drop the Postgres native enum types it created for
    # these columns — without this, a subsequent upgrade fails with
    # "type already exists" (same fix as later migrations).
    postgresql.ENUM(name='patient_admission_status').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='patient_language').drop(op.get_bind(), checkfirst=True)
