"""remove medication purpose cache, add comprehension feedback

Revision ID: 10e4cf4d4211
Revises: 261d5de4a45f
Create Date: 2026-09-05 01:58:53.161480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10e4cf4d4211'
down_revision: Union[str, None] = '261d5de4a45f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_comprehension_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('care_instruction_id', sa.UUID(), nullable=False),
    sa.Column('response', sa.Enum('UNDERSTOOD', 'HAS_QUESTION', 'ASK_CARE_TEAM', name='comprehension_response'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['care_instruction_id'], ['care_instructions.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_comprehension_feedback_care_instruction_id'), 'patient_comprehension_feedback', ['care_instruction_id'], unique=False)
    op.create_index(op.f('ix_patient_comprehension_feedback_created_at'), 'patient_comprehension_feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_patient_comprehension_feedback_patient_id'), 'patient_comprehension_feedback', ['patient_id'], unique=False)
    op.drop_table('medication_purpose_cache')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_purpose_cache',
    sa.Column('medication_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('purpose_text', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('prompt_version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('medication_name', name='medication_purpose_cache_pkey')
    )
    op.drop_index(op.f('ix_patient_comprehension_feedback_patient_id'), table_name='patient_comprehension_feedback')
    op.drop_index(op.f('ix_patient_comprehension_feedback_created_at'), table_name='patient_comprehension_feedback')
    op.drop_index(op.f('ix_patient_comprehension_feedback_care_instruction_id'), table_name='patient_comprehension_feedback')
    op.drop_table('patient_comprehension_feedback')
    # ### end Alembic commands ###
