"""add prn fields to administration_events

Revision ID: 13e32389741c
Revises: 06a3cd513143
Create Date: 2026-09-15 08:10:23.425381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e32389741c'
down_revision: Union[str, None] = '06a3cd513143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills the existing rows (the column is NOT NULL and
    # the table already has data), then dropped so the schema matches the
    # model, which sets the default in Python. Same pattern as the
    # identified_high_alert column.
    op.add_column(
        'administration_events',
        sa.Column('order_is_prn', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('administration_events', 'order_is_prn', server_default=None)
    op.add_column('administration_events', sa.Column('administration_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('administration_events', 'administration_reason')
    op.drop_column('administration_events', 'order_is_prn')
    # ### end Alembic commands ###
