"""add patient chat messages table

Revision ID: 261d5de4a45f
Revises: d917529fbba6
Create Date: 2026-09-04 11:25:49.190439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261d5de4a45f'
down_revision: Union[str, None] = 'd917529fbba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('PATIENT', 'ASSISTANT', name='patient_chat_role'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('emergency_flagged', sa.Boolean(), nullable=False),
    sa.Column('redirect_flagged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_chat_messages_created_at'), 'patient_chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_patient_chat_messages_patient_id'), 'patient_chat_messages', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_chat_messages_patient_id'), table_name='patient_chat_messages')
    op.drop_index(op.f('ix_patient_chat_messages_created_at'), table_name='patient_chat_messages')
    op.drop_table('patient_chat_messages')
    # ### end Alembic commands ###
