"""add administration_events table for module 2

Revision ID: 349efef042b5
Revises: a7c2e9f4d1b6
Create Date: 2026-09-05 07:37:57.902740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '349efef042b5'
down_revision: Union[str, None] = 'a7c2e9f4d1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administration_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('care_instruction_id', sa.UUID(), nullable=True),
    sa.Column('product_barcode', sa.String(length=200), nullable=False),
    sa.Column('verification_result', sa.Enum('VERIFIED', 'WARNING', 'BLOCKED', 'REVIEW_REQUIRED', name='administration_verification_result'), nullable=False),
    sa.Column('mismatch_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=False),
    sa.Column('administered_by', sa.UUID(), nullable=True),
    sa.Column('administered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['administered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['care_instruction_id'], ['care_instructions.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_administration_events_care_instruction_id'), 'administration_events', ['care_instruction_id'], unique=False)
    op.create_index(op.f('ix_administration_events_created_at'), 'administration_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_administration_events_patient_id'), 'administration_events', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_administration_events_patient_id'), table_name='administration_events')
    op.drop_index(op.f('ix_administration_events_created_at'), table_name='administration_events')
    op.drop_index(op.f('ix_administration_events_care_instruction_id'), table_name='administration_events')
    op.drop_table('administration_events')
    # ### end Alembic commands ###
