"""add reading_grade_level to patient_outputs

Revision ID: 4a80500a5ae6
Revises: bdec9040c64a
Create Date: 2026-09-14 10:55:06.585101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a80500a5ae6'
down_revision: Union[str, None] = 'bdec9040c64a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_outputs', sa.Column('reading_grade_level', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_outputs', 'reading_grade_level')
    # ### end Alembic commands ###
