"""create patient_outputs table

Revision ID: 5a6daee18c15
Revises: c9898ef37e7e
Create Date: 2026-09-02 14:32:37.813284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a6daee18c15'
down_revision: Union[str, None] = 'c9898ef37e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instruction_version_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('patient_text_en', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.Enum('PENDING', 'PASSED', 'FAILED', name='patient_output_validation_status'), nullable=False),
    sa.Column('validation_diff', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instruction_version_id'], ['instruction_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instruction_version_id', 'attempt_number', name='uq_patient_output_attempt')
    )
    op.create_index(op.f('ix_patient_outputs_instruction_version_id'), 'patient_outputs', ['instruction_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_outputs_instruction_version_id'), table_name='patient_outputs')
    op.drop_table('patient_outputs')
    # ### end Alembic commands ###

    # op.drop_table doesn't drop the Postgres native enum type it created for
    # this column — without this, a subsequent upgrade fails with "type already
    # exists" (see the same fix in earlier migrations).
    postgresql.ENUM(name='patient_output_validation_status').drop(op.get_bind(), checkfirst=True)
