"""add translations and patient care access tokens

Revision ID: 745b7818429a
Revises: 5a6daee18c15
Create Date: 2026-09-02 15:07:59.953575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '745b7818429a'
down_revision: Union[str, None] = '5a6daee18c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_care_access_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_care_access_tokens_patient_id'), 'patient_care_access_tokens', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_care_access_tokens_token_hash'), 'patient_care_access_tokens', ['token_hash'], unique=True)
    op.create_table('patient_output_translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_output_id', sa.UUID(), nullable=False),
    sa.Column('language', postgresql.ENUM('ENGLISH', 'TELUGU', 'HINDI', name='patient_language', create_type=False), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('validation_status', postgresql.ENUM('PENDING', 'PASSED', 'FAILED', name='patient_output_validation_status', create_type=False), nullable=False),
    sa.Column('validation_diff', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_output_id'], ['patient_outputs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_output_id', 'language', name='uq_translation_per_language')
    )
    op.create_index(op.f('ix_patient_output_translations_patient_output_id'), 'patient_output_translations', ['patient_output_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_output_translations_patient_output_id'), table_name='patient_output_translations')
    op.drop_table('patient_output_translations')
    op.drop_index(op.f('ix_patient_care_access_tokens_token_hash'), table_name='patient_care_access_tokens')
    op.drop_index(op.f('ix_patient_care_access_tokens_patient_id'), table_name='patient_care_access_tokens')
    op.drop_table('patient_care_access_tokens')
    # ### end Alembic commands ###
