"""add patient conditions table

Revision ID: 783f25857d92
Revises: 026be35d8d9e
Create Date: 2026-09-04 09:10:29.172051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783f25857d92'
down_revision: Union[str, None] = '026be35d8d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('condition_name', sa.String(length=255), nullable=False),
    sa.Column('documented_by', sa.UUID(), nullable=False),
    sa.Column('documented_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['documented_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_conditions_patient_id'), 'patient_conditions', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_conditions_patient_id'), table_name='patient_conditions')
    op.drop_table('patient_conditions')
    # ### end Alembic commands ###
