"""add encounters, medication clinical lifecycle, condition encounter link

Revision ID: 9850830ad17a
Revises: 10e4cf4d4211
Create Date: 2026-09-05 02:50:02.828177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9850830ad17a'
down_revision: Union[str, None] = '10e4cf4d4211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('encounter_type', sa.String(length=50), nullable=True),
    sa.Column('reason_for_visit', sa.Text(), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('discharge_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='encounter_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.add_column('care_instructions', sa.Column('encounter_id', sa.UUID(), nullable=True))
    # Unlike a brand-new table (where CREATE TABLE implicitly creates an
    # inline enum type), ALTER TABLE ADD COLUMN does NOT auto-create a
    # native Postgres enum type — it must exist first, or ADD COLUMN fails
    # with "type ... does not exist". create_type=False on the column's own
    # Enum then prevents a second, redundant creation attempt.
    clinical_status_enum = sa.Enum(
        'ACTIVE', 'COMPLETED', 'STOPPED', name='care_instruction_clinical_status'
    )
    clinical_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'care_instructions',
        sa.Column(
            'clinical_status',
            sa.Enum('ACTIVE', 'COMPLETED', 'STOPPED', name='care_instruction_clinical_status', create_type=False),
            nullable=True,
        ),
    )
    op.add_column('care_instructions', sa.Column('clinical_start_date', sa.Date(), nullable=True))
    op.add_column('care_instructions', sa.Column('clinical_end_date', sa.Date(), nullable=True))
    op.add_column('care_instructions', sa.Column('clinical_status_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('care_instructions', sa.Column('clinical_status_changed_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_care_instructions_encounter_id'), 'care_instructions', ['encounter_id'], unique=False)
    op.create_foreign_key(None, 'care_instructions', 'users', ['clinical_status_changed_by'], ['id'])
    op.create_foreign_key(None, 'care_instructions', 'encounters', ['encounter_id'], ['id'])
    op.add_column('patient_conditions', sa.Column('encounter_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_patient_conditions_encounter_id'), 'patient_conditions', ['encounter_id'], unique=False)
    op.create_foreign_key(None, 'patient_conditions', 'encounters', ['encounter_id'], ['id'])
    # ### end Alembic commands ###

    # Data backfill — deliberately scoped, NOT a column default. Only an
    # existing CareInstruction that is (a) already APPROVED and (b) a
    # MEDICATION-type instruction gets clinical_status = ACTIVE. Every
    # mobility/diet/wound-care/follow-up/general instruction, and every
    # medication instruction that never reached APPROVED, is left untouched
    # (clinical_status stays NULL) by simply not matching this WHERE clause
    # — see ClinicalStatus's docstring in app/instructions/models.py.
    # clinical_start_date uses approved_at's date as the best available
    # estimate, matching what approve() now does going forward for new
    # medication approvals — never created_at, which can predate the actual
    # approval by an arbitrary clarification back-and-forth.
    op.execute(
        """
        UPDATE care_instructions ci
        SET clinical_status = 'ACTIVE',
            clinical_start_date = ci.approved_at::date
        FROM instruction_versions iv
        JOIN structured_extractions se ON se.instruction_version_id = iv.id
        WHERE ci.current_version_id = iv.id
          AND se.instruction_type = 'MEDICATION'
          AND ci.status = 'APPROVED'
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient_conditions', type_='foreignkey')
    op.drop_index(op.f('ix_patient_conditions_encounter_id'), table_name='patient_conditions')
    op.drop_column('patient_conditions', 'encounter_id')
    op.drop_constraint(None, 'care_instructions', type_='foreignkey')
    op.drop_constraint(None, 'care_instructions', type_='foreignkey')
    op.drop_index(op.f('ix_care_instructions_encounter_id'), table_name='care_instructions')
    op.drop_column('care_instructions', 'clinical_status_changed_by')
    op.drop_column('care_instructions', 'clinical_status_changed_at')
    op.drop_column('care_instructions', 'clinical_end_date')
    op.drop_column('care_instructions', 'clinical_start_date')
    op.drop_column('care_instructions', 'clinical_status')
    sa.Enum(name='care_instruction_clinical_status').drop(op.get_bind(), checkfirst=True)
    op.drop_column('care_instructions', 'encounter_id')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_table('encounters')
    # ### end Alembic commands ###
