"""add procedure and nil by mouth to encounters

Revision ID: a3b6966e88d9
Revises: 09f46a08bd9b
Create Date: 2026-09-23 02:55:58.628640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3b6966e88d9'
down_revision: Union[str, None] = '09f46a08bd9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounters', sa.Column('planned_procedure', sa.Text(), nullable=True))
    op.add_column('encounters', sa.Column('nil_by_mouth_from', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('encounters', 'nil_by_mouth_from')
    op.drop_column('encounters', 'planned_procedure')
    # ### end Alembic commands ###
