"""create care_instructions and instruction_versions tables

Revision ID: a8e95807f918
Revises: 10a058489a8a
Create Date: 2026-09-02 13:37:02.122276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a8e95807f918'
down_revision: Union[str, None] = '10a058489a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: hand-adjusted — care_instructions.current_version_id and
    # instruction_versions.care_instruction_id form a genuine circular FK. The
    # current_version_id constraint is added via a separate op.create_foreign_key
    # below, after instruction_versions exists, instead of being inlined here.
    op.create_table('care_instructions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'NEEDS_REVIEW', 'READY_FOR_APPROVAL', 'APPROVED', 'REJECTED', name='instruction_status'), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_instructions_patient_id'), 'care_instructions', ['patient_id'], unique=False)
    op.create_table('instruction_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('care_instruction_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('ORIGINAL', 'CLARIFICATION', name='instruction_version_source'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['care_instruction_id'], ['care_instructions.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('care_instruction_id', 'version_number', name='uq_instruction_version_number')
    )
    op.create_index(op.f('ix_instruction_versions_care_instruction_id'), 'instruction_versions', ['care_instruction_id'], unique=False)
    # ### end Alembic commands ###

    op.create_foreign_key(
        'fk_care_instructions_current_version_id',
        'care_instructions', 'instruction_versions',
        ['current_version_id'], ['id'],
    )


def downgrade() -> None:
    # Must drop the cross-table FK before instruction_versions can be dropped.
    op.drop_constraint('fk_care_instructions_current_version_id', 'care_instructions', type_='foreignkey')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instruction_versions_care_instruction_id'), table_name='instruction_versions')
    op.drop_table('instruction_versions')
    op.drop_index(op.f('ix_care_instructions_patient_id'), table_name='care_instructions')
    op.drop_table('care_instructions')
    # ### end Alembic commands ###

    # op.drop_table doesn't drop the Postgres native enum types it created for
    # these columns — without this, a subsequent upgrade fails with
    # "type already exists".
    postgresql.ENUM(name='instruction_version_source').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='instruction_status').drop(op.get_bind(), checkfirst=True)
