"""add patient_allergies table

Revision ID: b9300aa8f28f
Revises: c1c27cbf9ddb
Create Date: 2026-09-14 08:51:00.498029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9300aa8f28f'
down_revision: Union[str, None] = 'c1c27cbf9ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_allergies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('allergen', sa.String(length=255), nullable=False),
    sa.Column('reaction', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('documented_by', sa.UUID(), nullable=False),
    sa.Column('documented_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['documented_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_allergies_patient_id'), 'patient_allergies', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_allergies_patient_id'), table_name='patient_allergies')
    op.drop_table('patient_allergies')
    # ### end Alembic commands ###
