"""add patient_teach_back_responses table

Revision ID: bdec9040c64a
Revises: b9300aa8f28f
Create Date: 2026-09-14 10:22:21.529301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdec9040c64a'
down_revision: Union[str, None] = 'b9300aa8f28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_teach_back_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('care_instruction_id', sa.UUID(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_facts', sa.JSON(), nullable=False),
    sa.Column('missing_facts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['care_instruction_id'], ['care_instructions.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_teach_back_responses_care_instruction_id'), 'patient_teach_back_responses', ['care_instruction_id'], unique=False)
    op.create_index(op.f('ix_patient_teach_back_responses_created_at'), 'patient_teach_back_responses', ['created_at'], unique=False)
    op.create_index(op.f('ix_patient_teach_back_responses_patient_id'), 'patient_teach_back_responses', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_teach_back_responses_patient_id'), table_name='patient_teach_back_responses')
    op.drop_index(op.f('ix_patient_teach_back_responses_created_at'), table_name='patient_teach_back_responses')
    op.drop_index(op.f('ix_patient_teach_back_responses_care_instruction_id'), table_name='patient_teach_back_responses')
    op.drop_table('patient_teach_back_responses')
    # ### end Alembic commands ###
