"""add identified product fields to administration_events

Revision ID: c1c27cbf9ddb
Revises: 159be66f1ce4
Create Date: 2026-09-08 10:57:28.325067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c27cbf9ddb'
down_revision: Union[str, None] = '159be66f1ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administration_events', sa.Column('identified_medication_name', sa.String(length=255), nullable=True))
    op.add_column('administration_events', sa.Column('identified_strength_value', sa.Float(), nullable=True))
    op.add_column('administration_events', sa.Column('identified_strength_unit', sa.String(length=50), nullable=True))
    op.add_column('administration_events', sa.Column('identified_formulation', sa.String(length=255), nullable=True))
    op.add_column('administration_events', sa.Column('identified_route', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('administration_events', 'identified_route')
    op.drop_column('administration_events', 'identified_formulation')
    op.drop_column('administration_events', 'identified_strength_unit')
    op.drop_column('administration_events', 'identified_strength_value')
    op.drop_column('administration_events', 'identified_medication_name')
    # ### end Alembic commands ###
