"""create structured_extractions table

Revision ID: c9898ef37e7e
Revises: a8e95807f918
Create Date: 2026-09-02 13:57:38.364892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9898ef37e7e'
down_revision: Union[str, None] = 'a8e95807f918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structured_extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instruction_version_id', sa.UUID(), nullable=False),
    sa.Column('instruction_type', sa.Enum('MEDICATION', 'MOBILITY', 'DIET', 'WOUND_CARE', 'FOLLOW_UP', 'GENERAL', name='structured_extraction_instruction_type'), nullable=True),
    sa.Column('extracted_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ambiguous_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('clarification_required_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completeness_status', sa.Enum('PASSED', 'NEEDS_CLARIFICATION', 'FAILED', name='structured_extraction_completeness_status'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instruction_version_id'], ['instruction_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_structured_extractions_instruction_version_id'), 'structured_extractions', ['instruction_version_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_structured_extractions_instruction_version_id'), table_name='structured_extractions')
    op.drop_table('structured_extractions')
    # ### end Alembic commands ###

    # op.drop_table doesn't drop the Postgres native enum types it created for
    # these columns — without this, a subsequent upgrade fails with
    # "type already exists" (see the same fix in the previous migration).
    postgresql.ENUM(name='structured_extraction_completeness_status').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='structured_extraction_instruction_type').drop(op.get_bind(), checkfirst=True)
