"""add medication purpose cache table

Revision ID: d917529fbba6
Revises: 783f25857d92
Create Date: 2026-09-04 10:10:04.643450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd917529fbba6'
down_revision: Union[str, None] = '783f25857d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_purpose_cache',
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('purpose_text', sa.String(length=500), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('medication_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medication_purpose_cache')
    # ### end Alembic commands ###
