import enum
import uuid
from datetime import date, datetime, timezone

from sqlalchemy import Date, DateTime, ForeignKey, String, text
from sqlalchemy import Enum as SAEnum
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.core.db import Base


class Language(str, enum.Enum):
    ENGLISH = "ENGLISH"
    TELUGU = "TELUGU"
    HINDI = "HINDI"


class AdmissionStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    DISCHARGED = "DISCHARGED"


class Patient(Base):
    __tablename__ = "patients"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Human-friendly clinical identifier (e.g. "P1001"), generated by a DB sequence —
    # never accepted from the client, so uniqueness is guaranteed at the DB level.
    patient_code: Mapped[str] = mapped_column(
        String(20),
        unique=True,
        index=True,
        nullable=False,
        server_default=text("'P' || nextval('patient_code_seq')"),
    )

    first_name: Mapped[str] = mapped_column(String(255), nullable=False)
    last_name: Mapped[str] = mapped_column(String(255), nullable=False)
    date_of_birth: Mapped[date] = mapped_column(Date, nullable=False)

    # Not unique — rooms are reused across patients over time.
    room_number: Mapped[str | None] = mapped_column(String(50), nullable=True)

    preferred_language: Mapped[Language] = mapped_column(
        SAEnum(Language, name="patient_language", native_enum=True),
        nullable=False,
        default=Language.ENGLISH,
    )
    admission_status: Mapped[AdmissionStatus] = mapped_column(
        SAEnum(AdmissionStatus, name="patient_admission_status", native_enum=True),
        nullable=False,
        default=AdmissionStatus.ACTIVE,
    )

    created_by: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
        nullable=False,
    )
