#!/usr/bin/env python3
"""Generate the band's spoken prompts as 8-bit PCM arrays (src/VoiceClips.h).

Uses macOS `say` and `afconvert`, so it runs on a Mac only; the generated
header is committed and the firmware build needs neither.

    python3 tools/make_voice.py            # rewrite src/VoiceClips.h

Each clip is normalised and gently compressed so it is intelligible on the
band's small speaker, then stored as unsigned 8-bit mono at 16 kHz
(~16 KB per second of speech).

LICENCE NOTE: Apple's system voices are fine for a prototype. Before the band
is used outside the bench, replace these with recordings that have a clear
licence for distribution (a recorded human voice, or a licensed TTS service).
"""
import array
import math
import os
import subprocess
import sys
import tempfile
import wave

VOICE = "Samantha"
RATE_WPM = 165
SAMPLE_RATE = 16000
PRE_EMPHASIS = 0.9   # first-order high-pass: lifts 1-4 kHz relative to the bass
DRIVE = 4.0          # soft-clip drive

# Short, calm, plain words. No diagnosis: the band says what it saw.
CLIPS = {
    "FALL": "Fall detected. Calling the nurse.",
    "CHECK": "Are you OK? Press the button if you are OK.",
    "CHECK_OK": "Thank you. No alert sent.",
    "NO_ANSWER": "No answer. Calling the nurse.",
    "HELP": "Help requested. Calling the nurse.",
    "NURSE_TOLD": "The nurse has been told.",
    "NURSE_COMING": "Don't worry. A nurse is coming.",
}


def render(text: str, tmp: str) -> array.array:
    aiff = os.path.join(tmp, "v.aiff")
    wav = os.path.join(tmp, "v.wav")
    subprocess.run(["say", "-v", VOICE, "-r", str(RATE_WPM), "-o", aiff, text], check=True)
    subprocess.run(["afconvert", "-f", "WAVE", "-d", f"LEI16@{SAMPLE_RATE}", "-c", "1", aiff, wav], check=True)
    with wave.open(wav) as w:
        pcm = array.array("h", w.readframes(w.getnframes()))
    return pcm


def to_u8(pcm: array.array) -> bytes:
    # Trim leading/trailing near-silence.
    floor = 300
    start = next((i for i, v in enumerate(pcm) if abs(v) > floor), 0)
    end = len(pcm) - next((i for i, v in enumerate(reversed(pcm)) if abs(v) > floor), 0)
    pcm = pcm[max(0, start - 400):min(len(pcm), end + 800)]
    # The band's speaker is a tiny cavity: loud at 2-3 kHz (where the alarm
    # tone sits), weak below ~800 Hz, where most speech energy is. Pre-emphasis
    # moves the energy up to where the speaker can play it, then hard soft-
    # clipping raises the average level. Bench: the first version (no
    # pre-emphasis, mild compression) was much quieter than the beeps.
    emph = [pcm[0]] + [pcm[i] - PRE_EMPHASIS * pcm[i - 1] for i in range(1, len(pcm))]
    peak = max(1.0, max(abs(v) for v in emph))
    out = bytearray()
    for v in emph:
        x = v / peak                                   # normalise to +-1
        x = math.tanh(DRIVE * x) / math.tanh(DRIVE)    # compress: louder on average
        out.append(max(0, min(255, int(round(128 + 127 * x)))))
    return bytes(out)


def main() -> int:
    here = os.path.dirname(os.path.abspath(__file__))
    target = os.path.join(here, "..", "src", "VoiceClips.h")
    lines = [
        "// GENERATED by tools/make_voice.py — do not edit by hand.",
        f"// Voice: macOS '{VOICE}' at {RATE_WPM} wpm; unsigned 8-bit mono, {SAMPLE_RATE} Hz.",
        "// Prototype only: replace with licensed recordings before use outside the bench.",
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "namespace voice {",
        f"static constexpr uint32_t kSampleRate = {SAMPLE_RATE};",
        "",
    ]
    total = 0
    with tempfile.TemporaryDirectory() as tmp:
        for name, text in CLIPS.items():
            data = to_u8(render(text, tmp))
            total += len(data)
            lines.append(f"// \"{text}\" ({len(data) / SAMPLE_RATE:.1f} s)")
            lines.append(f"static const uint8_t k{name}[{len(data)}] = {{")
            for i in range(0, len(data), 24):
                lines.append("  " + ",".join(str(b) for b in data[i:i + 24]) + ",")
            lines.append("};")
            lines.append("")
            print(f"{name:13s} {len(data) / SAMPLE_RATE:4.1f} s  {len(data) // 1024:3d} KB  {text}")
    lines.append("}  // namespace voice")
    lines.append("")
    with open(target, "w") as f:
        f.write("\n".join(lines))
    print(f"total {total // 1024} KB -> {os.path.normpath(target)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
