#!/usr/bin/env python3
"""SAFEHAVEN Module 3 — convert the design's TTF fonts into smooth (VLW) fonts
for the M5StickS3, as C headers in include/fonts/.

The wearable screens (design canvas: Space Grotesk + IBM Plex Sans) are drawn
with M5GFX, which renders anti-aliased "VLW" fonts: a big-endian header, one
28-byte metrics record per glyph sorted by code point, then one 8-bit alpha
bitmap per glyph. This script rasterises each (font, weight, pixel size,
character set) below with Pillow and writes that format.

Only the characters a screen actually uses are included, to keep flash small.

Usage (Pillow required; it is a build-time tool, not a firmware dependency):

    python3 -m venv /tmp/vlw && /tmp/vlw/bin/pip install pillow
    /tmp/vlw/bin/python tools/make_vlw.py <dir holding the .ttf files>

Fonts: Space Grotesk and IBM Plex Sans, both SIL Open Font License 1.1, from
github.com/google/fonts (ofl/spacegrotesk, ofl/ibmplexsans).
"""

import os
import struct
import sys

from PIL import Image, ImageDraw, ImageFont

SPACE_GROTESK = "spacegrotesk_SpaceGrotesk[wght].ttf"
PLEX_SANS = "ibmplexsans_IBMPlexSans[wdth,wght].ttf"

ASCII = "".join(chr(c) for c in range(0x20, 0x7F)) + "·"  # + middle dot
DIGITS_TIME = "0123456789:"
DIGITS_NUM = "0123456789.%"
UPPER = " ABCDEFGHIJKLMNOPQRSTUVWXYZ"

# (C name, ttf, weight, pixel size, characters). Sizes are REAL screen pixels:
# the design canvas is drawn at 2x, so a 72 px design clock is 36 px here.
FONTS = [
    ("font_clock",      SPACE_GROTESK, 600, 36, DIGITS_TIME),
    ("font_number",     SPACE_GROTESK, 600, 26, DIGITS_NUM),
    ("font_brand_lg",   SPACE_GROTESK, 600, 14, UPPER),
    ("font_brand_sm",   SPACE_GROTESK, 600, 9,  UPPER),
    ("font_title",      PLEX_SANS,     600, 14, ASCII),
    ("font_body",       PLEX_SANS,     400, 10, ASCII),
    ("font_body_bold",  PLEX_SANS,     600, 10, ASCII),
    ("font_small",      PLEX_SANS,     400, 9,  ASCII),
]


def load(path, weight, size):
    font = ImageFont.truetype(path, size)
    axes = font.get_variation_axes()
    values = []
    for axis in axes:
        name = axis.get("name", b"")
        name = name.decode() if isinstance(name, bytes) else name
        if name.lower().startswith("weight"):
            values.append(weight)
        else:  # width etc.: keep the default (normal) value
            values.append(axis.get("default", 100))
    if values:
        font.set_variation_by_axes(values)
    return font


def glyph(font, ch):
    """Return (width, height, x_advance, dY above baseline, dX, alpha bytes)."""
    advance = int(round(font.getlength(ch)))
    if ch == " ":
        return 0, 0, advance, 0, 0, b""
    x0, y0, x1, y1 = font.getbbox(ch, anchor="ls")
    w, h = x1 - x0, y1 - y0
    if w <= 0 or h <= 0:
        return 0, 0, advance, 0, 0, b""
    img = Image.new("L", (w, h), 0)
    ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255, anchor="ls")
    return w, h, advance, -y0, x0, img.tobytes()


def vlw(font, size, chars):
    ascent, descent = font.getmetrics()
    chars = sorted(set(chars), key=ord)
    glyphs = [(ord(c),) + glyph(font, c) for c in chars]
    out = bytearray(struct.pack(">6i", len(glyphs), 11, size, 0, ascent, descent))
    for code, w, h, adv, dy, dx, _ in glyphs:
        if w > 255 or adv > 255 or not -128 <= dx <= 127:
            raise ValueError(f"glyph {chr(code)!r} too large for VLW at {size}px")
        out += struct.pack(">7i", code, h, w, adv, dy, dx, 0)
    for *_, bitmap in glyphs:
        out += bitmap
    return bytes(out)


def header(name, data, desc):
    lines = [
        f"// {desc}",
        "// Generated by tools/make_vlw.py — do not edit by hand.",
        "#pragma once",
        "#include <stdint.h>",
        f"static const uint8_t {name}[{len(data)}] = {{",
    ]
    for i in range(0, len(data), 20):
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in data[i:i + 20]) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    src = sys.argv[1]
    dst = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "include", "fonts")
    os.makedirs(dst, exist_ok=True)
    total = 0
    for name, ttf, weight, size, chars in FONTS:
        font = load(os.path.join(src, ttf), weight, size)
        data = vlw(font, size, chars)
        family = ttf.split("_")[1].split("[")[0]
        desc = f"{family} {weight}, {size} px, {len(set(chars))} glyphs (SIL OFL 1.1)"
        with open(os.path.join(dst, name + ".h"), "w") as f:
            f.write(header(name, data, desc))
        total += len(data)
        print(f"{name:16s} {desc:52s} {len(data):6d} bytes")
    print(f"total {total} bytes")


if __name__ == "__main__":
    main()
