import type { AuditEvent } from '@/types/audit'

export type AuditEventCategory = 'info' | 'safety-warning' | 'approval' | 'patient-activity'

const CATEGORY_BY_EVENT_TYPE: Record<string, AuditEventCategory> = {
  INSTRUCTION_NEEDS_REVIEW: 'safety-warning',
  FACT_VALIDATION_FAILED: 'safety-warning',
  TRANSLATION_VALIDATION_FAILED: 'safety-warning',
  INSTRUCTION_REJECTED: 'safety-warning',
  INSTRUCTION_APPROVED: 'approval',
  CARE_PLAN_VIEWED: 'patient-activity',
  PATIENT_CHAT_EMERGENCY_FLAGGED: 'safety-warning',
  PATIENT_CHAT_TREATMENT_CHANGE_REDIRECTED: 'safety-warning',
  PATIENT_CHAT_WEB_SEARCH_USED: 'patient-activity',
  PATIENT_COMPREHENSION_NEEDS_ATTENTION: 'safety-warning',
}

export function auditEventCategory(eventType: string): AuditEventCategory {
  return CATEGORY_BY_EVENT_TYPE[eventType] ?? 'info'
}

function languageSuffix(event: AuditEvent): string {
  const language = event.event_metadata['language']
  return typeof language === 'string' ? ` (${language.charAt(0)}${language.slice(1).toLowerCase()})` : ''
}

export function auditEventDescription(event: AuditEvent): string {
  switch (event.event_type) {
    case 'USER_LOGIN':
      return 'Clinician logged in'
    case 'PATIENT_CREATED':
      return 'Patient record created'
    case 'PATIENT_UPDATED':
      return 'Patient record updated'
    case 'PATIENT_DISCHARGED':
      return 'Patient discharged'
    case 'INSTRUCTION_CREATED':
      return 'Care instruction created'
    case 'INSTRUCTION_ANALYSIS_STARTED':
      return 'AI analysis started'
    case 'INSTRUCTION_ANALYSIS_PASSED':
      return 'AI analysis passed — all required facts extracted'
    case 'INSTRUCTION_NEEDS_REVIEW':
      return event.event_metadata['reason'] === 'AI_EXTRACTION_FAILED'
        ? 'AI analysis failed — flagged for clinician review'
        : 'Flagged for clinician review — clarification needed'
    case 'CLARIFICATION_CREATED':
      return 'Clinician submitted a clarification'
    case 'PATIENT_OUTPUT_GENERATED':
      return 'Patient-friendly version generated by AI'
    case 'FACT_VALIDATION_PASSED':
      return 'Fact-preservation check passed'
    case 'FACT_VALIDATION_FAILED':
      return 'Fact-preservation check FAILED — blocked from patient view'
    case 'INSTRUCTION_APPROVED':
      return 'Instruction approved for patient viewing'
    case 'INSTRUCTION_REJECTED':
      return 'Instruction rejected by clinician'
    case 'TRANSLATION_CREATED':
      return `Translation generated${languageSuffix(event)}`
    case 'TRANSLATION_VALIDATION_PASSED':
      return `Translation safety check passed${languageSuffix(event)}`
    case 'TRANSLATION_VALIDATION_FAILED':
      return `Translation safety check FAILED${languageSuffix(event)} — blocked from patient view`
    case 'CARE_ACCESS_TOKEN_CREATED':
      return 'Patient care link created'
    case 'CARE_ACCESS_TOKEN_REVOKED':
      return event.event_metadata['reason'] === 'patient_discharged'
        ? 'Patient care link auto-revoked (discharge)'
        : 'Patient care link revoked'
    case 'CARE_PLAN_VIEWED':
      return 'Patient viewed their care plan'
    case 'PATIENT_CHAT_EMERGENCY_FLAGGED':
      return 'Patient chat: emergency response triggered'
    case 'PATIENT_CHAT_TREATMENT_CHANGE_REDIRECTED':
      return 'Patient chat: redirected to care team (treatment change)'
    case 'PATIENT_CHAT_WEB_SEARCH_USED':
      return 'Patient chat: answered using trusted medical web search'
    case 'PATIENT_COMPREHENSION_NEEDS_ATTENTION':
      return event.event_metadata['response'] === 'ASK_CARE_TEAM'
        ? 'Patient asked to be contacted by their care team'
        : 'Patient said they still have a question'
    default:
      return event.event_type
  }
}
